# -*- mode: ruby -*-
# vi: set ft=ruby :

# 建立多台VM，並且他们能够互相通信，假设一台是应用服务器、一台是redis服务器，只需要通过config.vm.define来定义不同的角色就可以了，配置文件进行如下设置：
Vagrant.configure("2") do |config|
  config.vm.define :web do |web|
    web.vm.box = "centos-7.3"
    web.vm.hostname = "web"
    web.vm.synced_folder ".", "/vagrant", disabled: true
    web.vm.network :private_network, ip: "192.168.33.10"
    web.vm.provider "virtualbox" do |v|
#       查看所有参数  VBoxManage modifyvm --help
#       v.name   = "web"
#       v.memory = "1024"
#       v.cpus   = "2"
      v.customize [ "modifyvm", :id, "--name", "web", "--memory", "1024", "--cpus", "2" ]
    end
  end

  config.vm.define :redis do |redis|
    redis.vm.box = "centos-7.3"
    redis.vm.hostname = "redis"
    redis.vm.synced_folder ".", "/vagrant", disabled: true
    redis.vm.network :private_network, ip: "192.168.33.11"
    redis.vm.provider "virtualbox" do |v|
#       查看所有参数  VBoxManage modifyvm --help
#       v.name   = "redis"
#       v.memory = "1024"
#       v.cpus   = "2"
      v.customize [ "modifyvm", :id, "--name", "redis", "--memory", "1024", "--cpus", "2" ]
    end
  end
end
