# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define :example1 do |example1|
    example1.vm.box = "centos-7.3" # 虚拟机模板的名称
    example1.vm.hostname = "template"
    example1.vm.synced_folder ".", "/vagrant", disabled: true
    example1.vm.network :private_network, ip: "192.168.35.11"
    template.ssh.username = "vagrant"
    template.ssh.password = "vagrant"
    example1.vm.provider "virtualbox" do |vb|
      vb.name = "centos-7.3-swarm"
      vb.gui = true
      vb.memory = "1024"
      vb.cpus = "2"
    end
  end
end

